# Compose file to run scylladb
version: '3.1'

services:
  scylla:
    image: scylladb/scylla:4.4.0
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/scylla
    environment:
      - SCYLLA_CLUSTER_NAME=scylla
      - SCYLLA_SEEDS=

volumes:
  data:
    driver: local
